// Rules ported from ClassicACE (bDekaru), AGPL-3.0: Source/ACE.Server/Factories/Tables/SpellDescriptors.cs
// @generated from ClassicACE's `Source/ACE.Server/Factories/Tables/SpellDescriptors.cs`; do not edit by hand

//! The tables of ClassicACE's `SpellDescriptors` under its Infiltration ruleset
//! (`Factories/Tables/SpellDescriptors.cs`).

use crate::static_map::StaticMap;
use empyrean_entity::enums::SpellId;

/// ClassicACE `SpellDescriptors.descriptors`, as its Infiltration ruleset sets it (`Dictionary<SpellId, string>`).
pub static DESCRIPTORS: StaticMap<SpellId, &str> = StaticMap::new(&DESCRIPTORS_ENTRIES, Some(&DESCRIPTORS_BY_KEY));
/// The entries of [`DESCRIPTORS`] in declaration order.
static DESCRIPTORS_ENTRIES: [(SpellId, &str); 164] = [
    (SpellId::StrengthOther1, "Strength"),
    (SpellId::StrengthSelf1, "Strength"),
    (SpellId::HealOther1, "Curing"),
    (SpellId::HealSelf1, "Healing"),
    (SpellId::InfuseMana1, "Infuse Mana"),
    (SpellId::InvulnerabilityOther1, "Invulnerability"),
    (SpellId::InvulnerabilitySelf1, "Invulnerability"),
    (SpellId::FireProtectionOther1, "Fire Protection"),
    (SpellId::FireProtectionSelf1, "Fire Protection"),
    (SpellId::ArmorOther1, "Protection"),
    (SpellId::ArmorSelf1, "Armor"),
    (SpellId::FlameBolt1, "Flame Bolt"),
    (SpellId::FrostBolt1, "Frost Bolt"),
    (SpellId::RejuvenationOther1, "Rejuvenation"),
    (SpellId::RejuvenationSelf1, "Rejuvenation"),
    (SpellId::AcidStream1, "Acid Stream"),
    (SpellId::ShockWave1, "Shock Wave"),
    (SpellId::LightningBolt1, "Lightning Bolt"),
    (SpellId::ForceBolt1, "Force Bolt"),
    (SpellId::WhirlingBlade1, "Blades"),
    (SpellId::RegenerationOther1, "Regeneration"),
    (SpellId::RegenerationSelf1, "Regeneration"),
    (SpellId::ManaRenewalOther1, "Mana Renewal"),
    (SpellId::ManaRenewalSelf1, "Mana Renewal"),
    (SpellId::ImpregnabilityOther1, "Impregnability"),
    (SpellId::ImpregnabilitySelf1, "Impregnability"),
    (SpellId::MagicResistanceOther1, "Magic Resistance"),
    (SpellId::MagicResistanceSelf1, "Magic Resistance"),
    (SpellId::LightWeaponsMasteryOther1, "Axe Mastery"),
    (SpellId::LightWeaponsMasterySelf1, "Axe Mastery"),
    (SpellId::FinesseWeaponsMasteryOther1, "Dagger Mastery"),
    (SpellId::FinesseWeaponsMasterySelf1, "Dagger Mastery"),
    (SpellId::MaceMasteryOther1, "Mace Mastery"),
    (SpellId::MaceMasterySelf1, "Mace Mastery"),
    (SpellId::SpearMasteryOther1, "Spear Mastery"),
    (SpellId::SpearMasterySelf1, "Spear Mastery"),
    (SpellId::StaffMasteryOther1, "Staff Mastery"),
    (SpellId::StaffMasterySelf1, "Staff Mastery"),
    (SpellId::HeavyWeaponsMasteryOther1, "Sword Mastery"),
    (SpellId::HeavyWeaponsMasterySelf1, "Sword Mastery"),
    (SpellId::UnarmedCombatMasteryOther1, "Unarmed Combat Mastery"),
    (SpellId::UnarmedCombatMasterySelf1, "Unarmed Combat Mastery"),
    (SpellId::MissileWeaponsMasteryOther1, "Bow Mastery"),
    (SpellId::MissileWeaponsMasterySelf1, "Bow Mastery"),
    (SpellId::CrossbowMasteryOther1, "Crossbow Mastery"),
    (SpellId::CrossbowMasterySelf1, "Crossbow Mastery"),
    (SpellId::AcidProtectionOther1, "Acid Protection"),
    (SpellId::AcidProtectionSelf1, "Acid Protection"),
    (SpellId::ThrownWeaponMasteryOther1, "Thrown Weapon Mastery"),
    (SpellId::ThrownWeaponMasterySelf1, "Thrown Weapon Mastery"),
    (SpellId::CreatureEnchantmentMasterySelf1, "Creature Enchantment"),
    (SpellId::CreatureEnchantmentMasteryOther1, "Creature Enchantment"),
    (SpellId::ItemEnchantmentMasterySelf1, "Item Enchantment"),
    (SpellId::ItemEnchantmentMasteryOther1, "Item Enchantment"),
    (SpellId::LifeMagicMasterySelf1, "Life Magic"),
    (SpellId::LifeMagicMasteryOther1, "Life Magic"),
    (SpellId::WarMagicMasterySelf1, "War Magic"),
    (SpellId::WarMagicMasteryOther1, "War Magic"),
    (SpellId::ManaMasterySelf1, "Mana Conversion"),
    (SpellId::ManaMasteryOther1, "Mana Conversion"),
    (SpellId::ArcaneEnlightenmentSelf1, "Arcane"),
    (SpellId::ArcaneEnlightenmentOther1, "Arcane"),
    (SpellId::ArmorExpertiseSelf1, "Armor Tinkering"),
    (SpellId::ArmorExpertiseOther1, "Armor Tinkering"),
    (SpellId::ItemExpertiseSelf1, "Item Tinkering"),
    (SpellId::ItemExpertiseOther1, "Item Tinkering"),
    (SpellId::MagicItemExpertiseSelf1, "Magic Item Tinkering"),
    (SpellId::MagicItemExpertiseOther1, "Magic Item Tinkering"),
    (SpellId::WeaponExpertiseSelf1, "Weapon Tinkering"),
    (SpellId::WeaponExpertiseOther1, "Weapon Tinkering"),
    (SpellId::MonsterAttunementSelf1, "Attunement"),
    (SpellId::MonsterAttunementOther1, "Attunement"),
    (SpellId::PersonAttunementSelf1, "Attunement"),
    (SpellId::PersonAttunementOther1, "Attunement"),
    (SpellId::DeceptionMasterySelf1, "Deception"),
    (SpellId::DeceptionMasteryOther1, "Deception"),
    (SpellId::HealingMasterySelf1, "Healing"),
    (SpellId::HealingMasteryOther1, "Healing"),
    (SpellId::LeadershipMasterySelf1, "Leadership"),
    (SpellId::LeadershipMasteryOther1, "Leadership"),
    (SpellId::LockpickMasterySelf1, "Lockpicking"),
    (SpellId::LockpickMasteryOther1, "Lockpicking"),
    (SpellId::FealtySelf1, "Fealty"),
    (SpellId::FealtyOther1, "Fealty"),
    (SpellId::JumpingMasterySelf1, "Jumping"),
    (SpellId::JumpingMasteryOther1, "Jumping"),
    (SpellId::SprintSelf1, "Sprinting"),
    (SpellId::SprintOther1, "Sprinting"),
    (SpellId::BludgeonProtectionSelf1, "Bludgeoning Protection"),
    (SpellId::BludgeonProtectionOther1, "Bludgeoning Protection"),
    (SpellId::ColdProtectionSelf1, "Cold Protection"),
    (SpellId::ColdProtectionOther1, "Cold Protection"),
    (SpellId::LightningProtectionSelf1, "Lightning Protection"),
    (SpellId::LightningProtectionOther1, "Lightning Protection"),
    (SpellId::BladeProtectionSelf1, "Blade Protection"),
    (SpellId::BladeProtectionOther1, "Blade Protection"),
    (SpellId::PiercingProtectionSelf1, "Piercing Protection"),
    (SpellId::PiercingProtectionOther1, "Piercing Protection"),
    (SpellId::RevitalizeSelf1, "Vitality"),
    (SpellId::RevitalizeOther1, "Vitality"),
    (SpellId::ManaBoostSelf1, "Mana"),
    (SpellId::ManaBoostOther1, "Mana"),
    (SpellId::InfuseHealth1, "Infuse Health"),
    (SpellId::InfuseStamina1, "Infuse Stamina"),
    (SpellId::HealthToStaminaOther1, "Health to Stamina"),
    (SpellId::HealthToStaminaSelf1, "Health to Stamina"),
    (SpellId::HealthToManaSelf1, "Health to Mana"),
    (SpellId::ManaToHealthOther1, "Mana to Health"),
    (SpellId::ManaToHealthSelf1, "Mana to Health"),
    (SpellId::ManaToStaminaSelf1, "Mana to Stamina"),
    (SpellId::ManaToStaminaOther1, "Mana to Stamina"),
    (SpellId::EnduranceSelf1, "Endurance"),
    (SpellId::EnduranceOther1, "Endurance"),
    (SpellId::CoordinationSelf1, "Coordination"),
    (SpellId::CoordinationOther1, "Coordination"),
    (SpellId::QuicknessSelf1, "Quickness"),
    (SpellId::QuicknessOther1, "Quickness"),
    (SpellId::FocusSelf1, "Focus"),
    (SpellId::FocusOther1, "Focus"),
    (SpellId::WillpowerSelf1, "Willpower"),
    (SpellId::WillpowerOther1, "Willpower"),
    (SpellId::StaminaToHealthOther1, "Stamina to Health"),
    (SpellId::StaminaToHealthSelf1, "Stamina to Health"),
    (SpellId::StaminaToManaOther1, "Stamina to Mana"),
    (SpellId::StaminaToManaSelf1, "Stamina to Mana"),
    (SpellId::HealthToManaOther1, "Health to Mana"),
    (SpellId::CookingMasteryOther1, "Cooking"),
    (SpellId::CookingMasterySelf1, "Cooking"),
    (SpellId::FletchingMasteryOther1, "Fletching"),
    (SpellId::FletchingMasterySelf1, "Fletching"),
    (SpellId::AlchemyMasteryOther1, "Alchemy"),
    (SpellId::AlchemyMasterySelf1, "Alchemy"),
    (SpellId::ShockwaveStreak1, "Shock Wave"),
    (SpellId::WhirlingBladeStreak1, "Blades"),
    (SpellId::ArcanumSalvagingSelf1, "Arcanum Salvaging"),
    (SpellId::ArcanumSalvagingOther1, "Arcanum Salvaging"),
    (SpellId::GearcraftMastery1, "Item Tinkering"),
    (SpellId::GearcraftMasterySelf1, "Item Tinkering"),
    (SpellId::TwoHandedMasteryOther1, "Two Handed Combat"),
    (SpellId::TwoHandedMasterySelf1, "Two Handed Combat"),
    (SpellId::Corrosion1, "Corrosion"),
    (SpellId::Corruption1, "Corruption"),
    (SpellId::VoidMagicMasteryOther1, "Void Magic"),
    (SpellId::VoidMagicMasterySelf1, "Void Magic"),
    (SpellId::DirtyFightingMasteryOther1, "Dirty Fighting"),
    (SpellId::DirtyFightingMasterySelf1, "Dirty Fighting"),
    (SpellId::DualWieldMasteryOther1, "Dual Wield"),
    (SpellId::DualWieldMasterySelf1, "Dual Wield"),
    (SpellId::RecklessnessMasteryOther1, "Recklessness"),
    (SpellId::RecklessnessMasterySelf1, "Recklessness"),
    (SpellId::ShieldMasteryOther1, "Shield"),
    (SpellId::ShieldMasterySelf1, "Shield"),
    (SpellId::SneakAttackMasteryOther1, "Sneak Attack"),
    (SpellId::SneakAttackMasterySelf1, "Sneak Attack"),
    (SpellId::SummoningMasteryOther1, "Summoning"),
    (SpellId::SummoningMasterySelf1, "Summoning"),
    (SpellId::BloodDrinkerSelf1, "Blood Drinker"),
    (SpellId::SwiftKillerSelf1, "Swift Killer"),
    (SpellId::DefenderSelf1, "Defender"),
    (SpellId::NetherBolt1, "Nether Bolt"),
    (SpellId::NetherArc1, "Nether Arc"),
    (SpellId::CurseFestering1, "Curse Festering"),
    (SpellId::CurseWeakness1, "Curse Weakness"),
    (SpellId::CurseDestructionOther1, "Curse Destruction"),
];
/// Indices into [`DESCRIPTORS_ENTRIES`] sorted by key.
static DESCRIPTORS_BY_KEY: [u32; 164] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 156, 157, 13,
    14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
    30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
    46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
    62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
    78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
    94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
    110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 158, 121, 122, 123, 124,
    125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 163,
    159, 160, 161, 162, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
    152, 153, 154, 155,
];
