//! The `DIK_*` / `DIMOFS_*` / `DIJOFS_*` / `DIV_*` name tables.
//!
//! Generated from the client's 248 key-semantic registrations, in registration order.
//!
//! **248 registrations**: 153 keyboard, 12 mouse,
//! 82 joystick and one virtual. The registration picks the table by the *third*
//! character of the name (`K`/`M`/`J`/`V`), which is why `DIMOFS_WHEEL` lands in the mouse table.
//!
//! Order is load order, and it matters: several offsets have more than one name (16 on the
//! keyboard alone -- `DIK_BACKSPACE` is `DIK_BACK`, `DIK_PGDN` is `DIK_NEXT`) and the primary name
//! is registered first. The semantic lookup in `spec` documents the deliberate approximation.

pub(crate) const KEYBOARD_NAMES: &[(&str, u16)] = &[
    ("DIK_ESCAPE", 0x01),
    ("DIK_1", 0x02),
    ("DIK_2", 0x03),
    ("DIK_3", 0x04),
    ("DIK_4", 0x05),
    ("DIK_5", 0x06),
    ("DIK_6", 0x07),
    ("DIK_7", 0x08),
    ("DIK_8", 0x09),
    ("DIK_9", 0x0A),
    ("DIK_0", 0x0B),
    ("DIK_MINUS", 0x0C),
    ("DIK_EQUALS", 0x0D),
    ("DIK_BACK", 0x0E),
    ("DIK_TAB", 0x0F),
    ("DIK_Q", 0x10),
    ("DIK_W", 0x11),
    ("DIK_E", 0x12),
    ("DIK_R", 0x13),
    ("DIK_T", 0x14),
    ("DIK_Y", 0x15),
    ("DIK_U", 0x16),
    ("DIK_I", 0x17),
    ("DIK_O", 0x18),
    ("DIK_P", 0x19),
    ("DIK_LBRACKET", 0x1A),
    ("DIK_RBRACKET", 0x1B),
    ("DIK_RETURN", 0x1C),
    ("DIK_LCONTROL", 0x1D),
    ("DIK_A", 0x1E),
    ("DIK_S", 0x1F),
    ("DIK_D", 0x20),
    ("DIK_F", 0x21),
    ("DIK_G", 0x22),
    ("DIK_H", 0x23),
    ("DIK_J", 0x24),
    ("DIK_K", 0x25),
    ("DIK_L", 0x26),
    ("DIK_SEMICOLON", 0x27),
    ("DIK_APOSTROPHE", 0x28),
    ("DIK_GRAVE", 0x29),
    ("DIK_LSHIFT", 0x2A),
    ("DIK_BACKSLASH", 0x2B),
    ("DIK_Z", 0x2C),
    ("DIK_X", 0x2D),
    ("DIK_C", 0x2E),
    ("DIK_V", 0x2F),
    ("DIK_B", 0x30),
    ("DIK_N", 0x31),
    ("DIK_M", 0x32),
    ("DIK_COMMA", 0x33),
    ("DIK_PERIOD", 0x34),
    ("DIK_SLASH", 0x35),
    ("DIK_RSHIFT", 0x36),
    ("DIK_MULTIPLY", 0x37),
    ("DIK_LMENU", 0x38),
    ("DIK_SPACE", 0x39),
    ("DIK_CAPITAL", 0x3A),
    ("DIK_F1", 0x3B),
    ("DIK_F2", 0x3C),
    ("DIK_F3", 0x3D),
    ("DIK_F4", 0x3E),
    ("DIK_F5", 0x3F),
    ("DIK_F6", 0x40),
    ("DIK_F7", 0x41),
    ("DIK_F8", 0x42),
    ("DIK_F9", 0x43),
    ("DIK_F10", 0x44),
    ("DIK_F11", 0x57),
    ("DIK_F12", 0x58),
    ("DIK_F13", 0x64),
    ("DIK_F14", 0x65),
    ("DIK_F15", 0x66),
    ("DIK_NUMLOCK", 0x45),
    ("DIK_SCROLL", 0x46),
    ("DIK_NUMPAD7", 0x47),
    ("DIK_NUMPAD8", 0x48),
    ("DIK_NUMPAD9", 0x49),
    ("DIK_SUBTRACT", 0x4A),
    ("DIK_NUMPAD4", 0x4B),
    ("DIK_NUMPAD5", 0x4C),
    ("DIK_NUMPAD6", 0x4D),
    ("DIK_ADD", 0x4E),
    ("DIK_NUMPAD1", 0x4F),
    ("DIK_NUMPAD2", 0x50),
    ("DIK_NUMPAD3", 0x51),
    ("DIK_NUMPAD0", 0x52),
    ("DIK_DECIMAL", 0x53),
    ("DIK_NUMPADENTER", 0x9C),
    ("DIK_RCONTROL", 0x9D),
    ("DIK_NUMPADCOMMA", 0xB3),
    ("DIK_DIVIDE", 0xB5),
    ("DIK_SYSRQ", 0xB7),
    ("DIK_RMENU", 0xB8),
    ("DIK_PAUSE", 0xC5),
    ("DIK_HOME", 0xC7),
    ("DIK_UP", 0xC8),
    ("DIK_PRIOR", 0xC9),
    ("DIK_LEFT", 0xCB),
    ("DIK_RIGHT", 0xCD),
    ("DIK_END", 0xCF),
    ("DIK_DOWN", 0xD0),
    ("DIK_NEXT", 0xD1),
    ("DIK_INSERT", 0xD2),
    ("DIK_DELETE", 0xD3),
    ("DIK_LWIN", 0xDB),
    ("DIK_RWIN", 0xDC),
    ("DIK_APPS", 0xDD),
    ("DIK_MUTE", 0xA0),
    ("DIK_CALCULATOR", 0xA1),
    ("DIK_PLAYPAUSE", 0xA2),
    ("DIK_MEDIASTOP", 0xA4),
    ("DIK_VOLUMEDOWN", 0xAE),
    ("DIK_VOLUMEUP", 0xB0),
    ("DIK_WEBHOME", 0xB2),
    ("DIK_WEBSEARCH", 0xE5),
    ("DIK_WEBFAVORITES", 0xE6),
    ("DIK_WEBREFRESH", 0xE7),
    ("DIK_WEBSTOP", 0xE8),
    ("DIK_WEBFORWARD", 0xE9),
    ("DIK_WEBBACK", 0xEA),
    ("DIK_MYCOMPUTER", 0xEB),
    ("DIK_MAIL", 0xEC),
    ("DIK_MEDIASELECT", 0xED),
    ("DIK_OEM_102", 0x56),
    ("DIK_ABNT_C1", 0x73),
    ("DIK_YEN", 0x7D),
    ("DIK_ABNT_C2", 0x7E),
    ("DIK_NUMPADEQUALS", 0x8D),
    ("DIK_PREVTRACK", 0x90),
    ("DIK_AT", 0x91),
    ("DIK_COLON", 0x92),
    ("DIK_UNDERLINE", 0x93),
    ("DIK_STOP", 0x95),
    ("DIK_AX", 0x96),
    ("DIK_UNLABELED", 0x97),
    ("DIK_NEXTTRACK", 0x99),
    ("DIK_BACKSPACE", 0x0E),
    ("DIK_NUMPADSTAR", 0x37),
    ("DIK_LALT", 0x38),
    ("DIK_CAPSLOCK", 0x3A),
    ("DIK_NUMPADMINUS", 0x4A),
    ("DIK_NUMPADPLUS", 0x4E),
    ("DIK_NUMPADPERIOD", 0x53),
    ("DIK_NUMPADSLASH", 0xB5),
    ("DIK_RALT", 0xB8),
    ("DIK_UPARROW", 0xC8),
    ("DIK_PGUP", 0xC9),
    ("DIK_LEFTARROW", 0xCB),
    ("DIK_RIGHTARROW", 0xCD),
    ("DIK_DOWNARROW", 0xD0),
    ("DIK_PGDN", 0xD1),
    ("DIK_CIRCUMFLEX", 0x90),
];

pub(crate) const MOUSE_NAMES: &[(&str, u16)] = &[
    ("DIMOFS_WHEEL", 0x08),
    ("DIMOFS_X", 0x00),
    ("DIMOFS_Y", 0x04),
    ("DIMOFS_Z", 0x08),
    ("DIMOFS_BUTTON0", 0x0C),
    ("DIMOFS_BUTTON1", 0x0D),
    ("DIMOFS_BUTTON2", 0x0E),
    ("DIMOFS_BUTTON3", 0x0F),
    ("DIMOFS_BUTTON4", 0x10),
    ("DIMOFS_BUTTON5", 0x11),
    ("DIMOFS_BUTTON6", 0x12),
    ("DIMOFS_BUTTON7", 0x13),
];

pub(crate) const JOYSTICK_NAMES: &[(&str, u16)] = &[
    ("DIJOFS_X", 0x00),
    ("DIJOFS_Y", 0x04),
    ("DIJOFS_Z", 0x08),
    ("DIJOFS_RX", 0x0C),
    ("DIJOFS_RY", 0x10),
    ("DIJOFS_RZ", 0x14),
    ("DIJOFS_SLIDER0", 0x18),
    ("DIJOFS_SLIDER1", 0x1C),
    ("DIJOFS_SLIDER(0)", 0x18),
    ("DIJOFS_SLIDER(1)", 0x1C),
    ("DIJOFS_POV0", 0x20),
    ("DIJOFS_POV1", 0x24),
    ("DIJOFS_POV2", 0x28),
    ("DIJOFS_POV3", 0x2C),
    ("DIJOFS_POV(0)", 0x20),
    ("DIJOFS_POV(1)", 0x24),
    ("DIJOFS_POV(2)", 0x28),
    ("DIJOFS_POV(3)", 0x2C),
    ("DIJOFS_BUTTON0", 0x30),
    ("DIJOFS_BUTTON1", 0x31),
    ("DIJOFS_BUTTON2", 0x32),
    ("DIJOFS_BUTTON3", 0x33),
    ("DIJOFS_BUTTON4", 0x34),
    ("DIJOFS_BUTTON5", 0x35),
    ("DIJOFS_BUTTON6", 0x36),
    ("DIJOFS_BUTTON7", 0x37),
    ("DIJOFS_BUTTON8", 0x38),
    ("DIJOFS_BUTTON9", 0x39),
    ("DIJOFS_BUTTON10", 0x3A),
    ("DIJOFS_BUTTON11", 0x3B),
    ("DIJOFS_BUTTON12", 0x3C),
    ("DIJOFS_BUTTON13", 0x3D),
    ("DIJOFS_BUTTON14", 0x3E),
    ("DIJOFS_BUTTON15", 0x3F),
    ("DIJOFS_BUTTON16", 0x40),
    ("DIJOFS_BUTTON17", 0x41),
    ("DIJOFS_BUTTON18", 0x42),
    ("DIJOFS_BUTTON19", 0x43),
    ("DIJOFS_BUTTON20", 0x44),
    ("DIJOFS_BUTTON21", 0x45),
    ("DIJOFS_BUTTON22", 0x46),
    ("DIJOFS_BUTTON23", 0x47),
    ("DIJOFS_BUTTON24", 0x48),
    ("DIJOFS_BUTTON25", 0x49),
    ("DIJOFS_BUTTON26", 0x4A),
    ("DIJOFS_BUTTON27", 0x4B),
    ("DIJOFS_BUTTON28", 0x4C),
    ("DIJOFS_BUTTON29", 0x4D),
    ("DIJOFS_BUTTON30", 0x4E),
    ("DIJOFS_BUTTON31", 0x4F),
    ("DIJOFS_BUTTON(0)", 0x30),
    ("DIJOFS_BUTTON(1)", 0x31),
    ("DIJOFS_BUTTON(2)", 0x32),
    ("DIJOFS_BUTTON(3)", 0x33),
    ("DIJOFS_BUTTON(4)", 0x34),
    ("DIJOFS_BUTTON(5)", 0x35),
    ("DIJOFS_BUTTON(6)", 0x36),
    ("DIJOFS_BUTTON(7)", 0x37),
    ("DIJOFS_BUTTON(8)", 0x38),
    ("DIJOFS_BUTTON(9)", 0x39),
    ("DIJOFS_BUTTON(10)", 0x3A),
    ("DIJOFS_BUTTON(11)", 0x3B),
    ("DIJOFS_BUTTON(12)", 0x3C),
    ("DIJOFS_BUTTON(13)", 0x3D),
    ("DIJOFS_BUTTON(14)", 0x3E),
    ("DIJOFS_BUTTON(15)", 0x3F),
    ("DIJOFS_BUTTON(16)", 0x40),
    ("DIJOFS_BUTTON(17)", 0x41),
    ("DIJOFS_BUTTON(18)", 0x42),
    ("DIJOFS_BUTTON(19)", 0x43),
    ("DIJOFS_BUTTON(20)", 0x44),
    ("DIJOFS_BUTTON(21)", 0x45),
    ("DIJOFS_BUTTON(22)", 0x46),
    ("DIJOFS_BUTTON(23)", 0x47),
    ("DIJOFS_BUTTON(24)", 0x48),
    ("DIJOFS_BUTTON(25)", 0x49),
    ("DIJOFS_BUTTON(26)", 0x4A),
    ("DIJOFS_BUTTON(27)", 0x4B),
    ("DIJOFS_BUTTON(28)", 0x4C),
    ("DIJOFS_BUTTON(29)", 0x4D),
    ("DIJOFS_BUTTON(30)", 0x4E),
    ("DIJOFS_BUTTON(31)", 0x4F),
];

pub(crate) const VIRTUAL_NAMES: &[(&str, u16)] = &[("DIV_MOUSELOOK", 0x01)];

use crate::InputMapId;

/// The action names are the shared action vocabulary's; the key, device and input-map names
/// above and below are this crate's own.
pub use dereth_client_contract::actions::names::{action_for_enum_name, enum_name_for_action};

#[must_use]
pub fn enum_name_for_input_map(m: InputMapId) -> String {
    crate::maps::ENUM_NAMES
        .iter()
        .find(|(k, _)| *k == m)
        .map_or_else(|| m.0.to_string(), |(_, n)| (*n).to_owned())
}

/// The input-map parser's "ERROR - invalid input map name" test.
#[must_use]
pub fn input_map_for_enum_name(name: &str) -> Option<InputMapId> {
    crate::maps::ENUM_NAMES
        .iter()
        .find(|(_, n)| *n == name)
        .map(|(k, _)| *k)
        .or_else(|| name.parse().ok().map(InputMapId))
}
