#[cfg(feature = "real-content")]
pub(crate) mod bare_body;
pub(crate) mod character_options_and_queries;
pub(crate) mod chargen;
pub(crate) mod death_xp;
pub(crate) mod enter_world;
pub(crate) mod login;
pub(crate) mod skill_proficiency;
pub(crate) mod stats;
pub(crate) mod stats_in_the_world;
