// Ported from ACE (ACEmulator), AGPL-3.0: Source/ACE.Database/Models/Shard/BiotaPropertiesEmoteAction.cs
//! `BiotaPropertiesEmoteAction`: a row of the `shard` database (Entity Framework model).

// ACE: BiotaPropertiesEmoteAction
#[derive(Debug, Clone, Default, PartialEq)]
pub struct BiotaPropertiesEmoteAction {
    // ACE: BiotaPropertiesEmoteAction.Id
    pub id: u32,
    // ACE: BiotaPropertiesEmoteAction.EmoteId
    pub emote_id: u32,
    // ACE: BiotaPropertiesEmoteAction.Order
    pub order: u32,
    // ACE: BiotaPropertiesEmoteAction.Type
    pub r#type: u32,
    // ACE: BiotaPropertiesEmoteAction.Delay
    pub delay: f32,
    // ACE: BiotaPropertiesEmoteAction.Extent
    pub extent: f32,
    // ACE: BiotaPropertiesEmoteAction.Motion
    pub motion: Option<u32>,
    // ACE: BiotaPropertiesEmoteAction.Message
    pub message: Option<String>,
    // ACE: BiotaPropertiesEmoteAction.TestString
    pub test_string: Option<String>,
    // ACE: BiotaPropertiesEmoteAction.Min
    pub min: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.Max
    pub max: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.Min64
    pub min_64: Option<i64>,
    // ACE: BiotaPropertiesEmoteAction.Max64
    pub max_64: Option<i64>,
    // ACE: BiotaPropertiesEmoteAction.MinDbl
    pub min_dbl: Option<f64>,
    // ACE: BiotaPropertiesEmoteAction.MaxDbl
    pub max_dbl: Option<f64>,
    // ACE: BiotaPropertiesEmoteAction.Stat
    pub stat: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.Display
    pub display: Option<bool>,
    // ACE: BiotaPropertiesEmoteAction.Amount
    pub amount: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.Amount64
    pub amount_64: Option<i64>,
    // ACE: BiotaPropertiesEmoteAction.HeroXP64
    pub hero_xp_64: Option<i64>,
    // ACE: BiotaPropertiesEmoteAction.Percent
    pub percent: Option<f64>,
    // ACE: BiotaPropertiesEmoteAction.SpellId
    pub spell_id: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.WealthRating
    pub wealth_rating: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.TreasureClass
    pub treasure_class: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.TreasureType
    pub treasure_type: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.PScript
    pub p_script: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.Sound
    pub sound: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.DestinationType
    pub destination_type: Option<i8>,
    // ACE: BiotaPropertiesEmoteAction.WeenieClassId
    pub weenie_class_id: Option<u32>,
    // ACE: BiotaPropertiesEmoteAction.StackSize
    pub stack_size: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.Palette
    pub palette: Option<i32>,
    // ACE: BiotaPropertiesEmoteAction.Shade
    pub shade: Option<f32>,
    // ACE: BiotaPropertiesEmoteAction.TryToBond
    pub try_to_bond: Option<bool>,
    // ACE: BiotaPropertiesEmoteAction.ObjCellId
    pub obj_cell_id: Option<u32>,
    // ACE: BiotaPropertiesEmoteAction.OriginX
    pub origin_x: Option<f32>,
    // ACE: BiotaPropertiesEmoteAction.OriginY
    pub origin_y: Option<f32>,
    // ACE: BiotaPropertiesEmoteAction.OriginZ
    pub origin_z: Option<f32>,
    // ACE: BiotaPropertiesEmoteAction.AnglesW
    pub angles_w: Option<f32>,
    // ACE: BiotaPropertiesEmoteAction.AnglesX
    pub angles_x: Option<f32>,
    // ACE: BiotaPropertiesEmoteAction.AnglesY
    pub angles_y: Option<f32>,
    // ACE: BiotaPropertiesEmoteAction.AnglesZ
    pub angles_z: Option<f32>,
}
