// Ported from ACE (ACEmulator), AGPL-3.0: Source/ACE.Server/WorldObjects/WorldObject_Decay.cs
//! Port of `Source/ACE.Server/WorldObjects/WorldObject_Decay.cs`: objects on a landblock rotting
//! away (dropped items, corpses, projectiles), and `DeleteObject`.
//!
//! Members are free functions over `(w, this)`. The landblock heartbeat (`Landblock.Tick`) calls
//! [`is_decayable`] and [`decay`] for each of its objects every 5 seconds.

use empyrean_common::dotnet::datetime::TimeSpan;
use empyrean_entity::enums::{Placement, PlayScript};
use empyrean_entity::{ObjectGuid, Position};

use crate::dispatch;
use crate::entity::actions::action_chain::ActionChain;
use crate::entity::actions::i_actor::Actor;
use crate::world_objects::world_object::WorldObject;
use crate::world_objects::{container, corpse, creature_equipment, player_inventory};
use crate::World;

/// Non-property fields declared in `WorldObject_Decay.cs`.
#[derive(Debug, Default)]
pub struct WorldObjectDecayFields {
    // ACE: WorldObject.decayCompleted
    pub decay_completed: bool,
}

// ACE: WorldObject.DefaultTimeToRot
/// The default number of seconds for a object on a landblock to disappear. Current default is 5
/// minutes. (A `protected` settable property in ACE that nothing assigns, so a constant here.)
pub const DEFAULT_TIME_TO_ROT: f64 = 300.0;

fn obj(w: &World, this: ObjectGuid) -> &WorldObject {
    w.objects.get(this).unwrap_or_else(|| {
        panic!(
            "System.NullReferenceException: object 0x{:08X} is not in World.objects",
            this.full()
        )
    })
}

fn obj_mut(w: &mut World, this: ObjectGuid) -> &mut WorldObject {
    w.objects.get_mut(this).unwrap_or_else(|| {
        panic!(
            "System.NullReferenceException: object 0x{:08X} is not in World.objects",
            this.full()
        )
    })
}

/// `decayCompleted`.
#[must_use]
pub fn decay_completed(o: &WorldObject) -> bool {
    o.wo.world_object_decay.decay_completed
}

// ACE: WorldObject.IsDecayable
/// A decayable object is one that, when it exists on a landblock, would decay (rot) over time.
/// When it rots, it would be destroyed, and removed from the landblock. In most cases, these
/// should be player dropped items or corpses. It can also be a missile or spell projectile.
/// Items that have a TimeToRot value of -1 will return false. Generators and items still linked
/// to a generator will return false.
#[must_use]
pub fn is_decayable(w: &World, this: ObjectGuid) -> bool {
    let o = obj(w, this);
    if !o.guid.is_dynamic() {
        return false;
    }

    // Don't rot generators, and items that were generated by a generator
    // If the item was generated by a generator and then picked up by a player, the wo.Generator property would be set to null.
    if o.is_generator() || o.wo.world_object_generators.generator.is_some() {
        return false;
    }

    // Don't rot items with lifespan, they'll handle their own version of decay.
    if o.lifespan().is_some() {
        return false;
    }

    if let Some(time_to_rot) = o.time_to_rot() {
        #[allow(clippy::float_cmp)] // C#'s `TimeToRot != -1`
        return time_to_rot != -1.0; // -1 = Never Rot
    }

    true
}

/// `PropertyManager.GetBool("corpse_decay_tick_logging").Item`.
fn corpse_decay_tick_logging(w: &World) -> bool {
    crate::managers::property_manager::get_bool(w, "corpse_decay_tick_logging", false, true).item
}

fn name(w: &World, this: ObjectGuid) -> String {
    dispatch::name::name(w, this).unwrap_or_default()
}

/// `double?` as C#'s string interpolation prints it (empty when null).
fn opt(v: Option<f64>) -> String {
    v.map(|v| v.to_string()).unwrap_or_default()
}

// ACE: WorldObject.Decay
pub fn decay(w: &mut World, this: ObjectGuid, elapsed: TimeSpan) {
    // http://asheron.wikia.com/wiki/Item_Decay

    if decay_completed(obj(w, this)) {
        return;
    }

    let previous_ttr = obj(w, this).time_to_rot();

    let is_corpse = obj(w, this).is_corpse();
    let has_level = obj(w, this).level().is_some();

    if previous_ttr.is_none() {
        obj_mut(w, this).set_time_to_rot(Some(DEFAULT_TIME_TO_ROT));

        if is_corpse && has_level {
            log::info!(
                "[CORPSE] {} (0x{}).Decay: TimeToRot had no value, set to {}",
                name(w, this),
                this,
                DEFAULT_TIME_TO_ROT
            );
        }

        return;
    }

    if is_corpse {
        if !obj(w, this)
            .container
            .as_ref()
            .is_some_and(|c| c.container.inventory_loaded)
        {
            return;
        }

        let inventory_count = container::inventory(obj(w, this)).len();
        if inventory_count == 0
            && obj(w, this)
                .time_to_rot()
                .is_some_and(|t| t > corpse::EMPTY_DECAY_TIME)
        {
            obj_mut(w, this).set_time_to_rot(Some(corpse::EMPTY_DECAY_TIME));
            if has_level && corpse_decay_tick_logging(w) {
                log::info!(
                    "[CORPSE] {} (0x{}).Decay({}): InventoryLoaded = {} | Inventory.Count = {} | previous TimeToRot: {} | current TimeToRot: {}",
                    name(w, this),
                    this,
                    elapsed,
                    true,
                    inventory_count,
                    opt(previous_ttr),
                    opt(obj(w, this).time_to_rot())
                );
            }
            return;
        }
    }

    if obj(w, this).time_to_rot().is_some_and(|t| t > 0.0) {
        let time_to_rot = obj(w, this)
            .time_to_rot()
            .map(|t| t - elapsed.total_seconds());
        obj_mut(w, this).set_time_to_rot(time_to_rot);

        if is_corpse && has_level && corpse_decay_tick_logging(w) {
            log::info!(
                "[CORPSE] {} (0x{}).Decay({}): previous TimeToRot: {} | current TimeToRot: {}",
                name(w, this),
                this,
                elapsed,
                opt(previous_ttr),
                opt(time_to_rot)
            );
        }

        // Is there still time left?
        if time_to_rot.is_some_and(|t| t > 0.0) {
            return;
        }

        obj_mut(w, this).set_time_to_rot(Some(-2.0)); // We force it to -2 to make sure it doesn't end up at 0 or -1. 0 indicates instant rot. -1 indicates no rot. 0 and -1 can be found in weenie defaults

        if is_corpse && has_level && corpse_decay_tick_logging(w) {
            log::info!(
                "[CORPSE] {} (0x{}).Decay({}): previous TimeToRot: {} | current TimeToRot: {}",
                name(w, this),
                this,
                elapsed,
                opt(previous_ttr),
                opt(obj(w, this).time_to_rot())
            );
        }
    }

    let o = obj(w, this);
    if o.is_container() && o.is_open() {
        // If you wanted to add a grace period to the container to give Player B more time to open it after Player A closes it, it would go here.

        return;
    }

    // Time to rot has elapsed, time to disappear...
    obj_mut(w, this).wo.world_object_decay.decay_completed = true;

    // If this is a player corpse, puke out the corpses contents onto the landblock
    if is_corpse && !corpse::fields(w, this).is_monster {
        let inventory_guids: Vec<ObjectGuid> =
            container::inventory(obj(w, this)).keys().copied().collect();

        let mut puked_items = String::new();

        for guid in inventory_guids {
            if let Some(item) = container::try_remove_from_inventory_with_item(w, this, guid, false)
            {
                let mut location = Position::from_position(
                    &obj(w, this)
                        .location()
                        .expect("ACE: corpse.Location is null (NullReferenceException)"),
                );
                let obj_scale = obj(w, item).obj_scale().unwrap_or(1.0);
                location.position_z += 0.05 * obj_scale;
                let item_obj = obj_mut(w, item);
                item_obj.set_location(Some(location));
                item_obj.set_placement(Some(Placement::Resting)); // This is needed to make items lay flat on the ground.
                let current_landblock = obj(w, this)
                    .current_landblock
                    .expect("ACE: CurrentLandblock is null (NullReferenceException)");
                crate::entity::landblock::add_world_object(w, current_landblock, item);
                dispatch::save_biota_to_database::save_biota_to_database(w, item, true);
                puked_items.push_str(&format!("{} (0x{:08X}), ", name(w, item), item.full()));
            }
        }

        if puked_items.ends_with(", ") {
            puked_items.truncate(puked_items.len() - 2);
        }

        let loc = obj(w, this)
            .location()
            .map(|l| l.to_loc_string())
            .unwrap_or_default();
        let placed = if puked_items.is_empty() {
            String::new()
        } else {
            format!(" and placed the following items on the landblock: {puked_items}")
        };
        log::info!(
            "[CORPSE] {} (0x{}) at {loc} has decayed{placed}.",
            name(w, this),
            this
        );
    }

    if is_corpse {
        let msg = crate::network::game_messages::messages::game_message_script::game_message_script(
            this,
            PlayScript::Destroy,
            1.0,
        );
        crate::world_objects::world_object_networking::enqueue_broadcast(w, this, true, &[msg]);

        let mut action_chain = ActionChain::new();
        action_chain.add_delay_seconds(w, f64::from(1.0f32));
        action_chain.add_action(Actor::Object(this), move |w: &mut World| destroy(w, this));
        action_chain.enqueue_chain(w);
    } else {
        destroy(w, this);
    }
}

/// `Destroy()` (`WorldObject.cs`; defaults `raiseNotifyOfDestructionEvent = true`,
/// `fromLandblockUnload = false`).
fn destroy(w: &mut World, this: ObjectGuid) {
    if w.objects.contains(this) {
        crate::world_objects::world_object::destroy(w, this, true, false);
    }
}

// ACE: WorldObject.DeleteObject
/// Unequips or removes this object from its wielder or `root_owner` (ACE's default: `null`), then
/// destroys it.
pub fn delete_object(w: &mut World, this: ObjectGuid, root_owner: Option<ObjectGuid>) {
    if let Some(wielder) = obj(w, this).wielder {
        let wielder_obj = obj(w, wielder);
        if wielder_obj.is_player() {
            player_inventory::try_dequip_object_with_networking(
                w,
                wielder,
                this,
                player_inventory::DequipObjectAction::ConsumeItem,
            );
        } else if wielder_obj.is_creature() {
            creature_equipment::try_unwield_object_with_broadcasting(w, wielder, this, false);
        }
    } else if let Some(root_owner) = root_owner {
        if obj(w, root_owner).is_player() {
            player_inventory::try_remove_from_inventory_with_networking(
                w,
                root_owner,
                this,
                player_inventory::RemoveFromInventoryAction::ConsumeItem,
            );
        } else {
            container::try_remove_from_inventory(w, root_owner, this, false);
        }
    }
    destroy(w, this);
}
