// Ported from ACE (ACEmulator), AGPL-3.0: Source/ACE.Database/Models/World/Spell.cs
//! `Spell`: one row of the world-database table `spell`.

use empyrean_common::dotnet::DotNetDateTime;

/// Spell Table Extended Data
// ACE: Spell
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Spell {
    /// Unique Id of this Spell
    pub id: u32,
    pub name: String,
    pub stat_mod_type: Option<u32>,
    pub stat_mod_key: Option<u32>,
    pub stat_mod_val: Option<f32>,
    pub e_type: Option<u32>,
    pub base_intensity: Option<i32>,
    pub variance: Option<i32>,
    pub wcid: Option<u32>,
    pub num_projectiles: Option<i32>,
    pub num_projectiles_variance: Option<i32>,
    pub spread_angle: Option<f32>,
    pub vertical_angle: Option<f32>,
    pub default_launch_angle: Option<f32>,
    pub non_tracking: Option<bool>,
    pub create_offset_origin_x: Option<f32>,
    pub create_offset_origin_y: Option<f32>,
    pub create_offset_origin_z: Option<f32>,
    pub padding_origin_x: Option<f32>,
    pub padding_origin_y: Option<f32>,
    pub padding_origin_z: Option<f32>,
    pub dims_origin_x: Option<f32>,
    pub dims_origin_y: Option<f32>,
    pub dims_origin_z: Option<f32>,
    pub peturbation_origin_x: Option<f32>,
    pub peturbation_origin_y: Option<f32>,
    pub peturbation_origin_z: Option<f32>,
    pub imbued_effect: Option<u32>,
    pub slayer_creature_type: Option<i32>,
    pub slayer_damage_bonus: Option<f32>,
    pub crit_freq: Option<f64>,
    pub crit_multiplier: Option<f64>,
    pub ignore_magic_resist: Option<i32>,
    pub elemental_modifier: Option<f64>,
    pub drain_percentage: Option<f32>,
    pub damage_ratio: Option<f32>,
    pub damage_type: Option<i32>,
    pub boost: Option<i32>,
    pub boost_variance: Option<i32>,
    pub source: Option<i32>,
    pub destination: Option<i32>,
    pub proportion: Option<f32>,
    pub loss_percent: Option<f32>,
    pub source_loss: Option<i32>,
    pub transfer_cap: Option<i32>,
    pub max_boost_allowed: Option<i32>,
    pub transfer_bitfield: Option<u32>,
    pub index: Option<i32>,
    pub link: Option<i32>,
    pub position_obj_cell_id: Option<u32>,
    pub position_origin_x: Option<f32>,
    pub position_origin_y: Option<f32>,
    pub position_origin_z: Option<f32>,
    pub position_angles_w: Option<f32>,
    pub position_angles_x: Option<f32>,
    pub position_angles_y: Option<f32>,
    pub position_angles_z: Option<f32>,
    pub min_power: Option<i32>,
    pub max_power: Option<i32>,
    pub power_variance: Option<f32>,
    pub dispel_school: Option<i32>,
    pub align: Option<i32>,
    pub number: Option<i32>,
    pub number_variance: Option<f32>,
    pub dot_duration: Option<f64>,
    pub last_modified: DotNetDateTime,
}
