// Ported from ACE (ACEmulator), AGPL-3.0: Source/ACE.Server/Factories/Tables/MaterialTable.cs
// @generated from ACE's `Source/ACE.Server/Factories/Tables/MaterialTable.cs`; do not edit by hand

//! The literal data of ACE's `MaterialTable` (`Factories/Tables/MaterialTable.cs`).

use crate::static_map::StaticMap;
use empyrean_entity::enums::MaterialType;

/// ACE `MaterialTable.ValueMod` (`Dictionary<MaterialType, float>`).
pub static VALUE_MOD: StaticMap<MaterialType, f32> = StaticMap::new(&VALUE_MOD_ENTRIES, None);
/// The entries of [`VALUE_MOD`] in declaration order.
static VALUE_MOD_ENTRIES: [(MaterialType, f32); 72] = [
    (MaterialType::Ceramic, 0.2),
    (MaterialType::Porcelain, 1.0),
    (MaterialType::Linen, 0.0),
    (MaterialType::Satin, 1.2),
    (MaterialType::Silk, 1.5),
    (MaterialType::Velvet, 1.2),
    (MaterialType::Wool, 0.0),
    (MaterialType::Agate, 1.4),
    (MaterialType::Amber, 1.1),
    (MaterialType::Amethyst, 2.3),
    (MaterialType::Aquamarine, 2.8),
    (MaterialType::Azurite, 2.3),
    (MaterialType::BlackGarnet, 2.4),
    (MaterialType::BlackOpal, 2.4),
    (MaterialType::Bloodstone, 1.5),
    (MaterialType::Carnelian, 2.1),
    (MaterialType::Citrine, 2.3),
    (MaterialType::Diamond, 6.0),
    (MaterialType::Emerald, 4.0),
    (MaterialType::FireOpal, 2.5),
    (MaterialType::GreenGarnet, 4.0),
    (MaterialType::GreenJade, 1.7),
    (MaterialType::Hematite, 1.9),
    (MaterialType::ImperialTopaz, 4.7),
    (MaterialType::Jet, 2.6),
    (MaterialType::LapisLazuli, 1.8),
    (MaterialType::LavenderJade, 2.2),
    (MaterialType::Malachite, 1.5),
    (MaterialType::Moonstone, 2.0),
    (MaterialType::Onyx, 1.2),
    (MaterialType::Opal, 2.3),
    (MaterialType::Peridot, 2.9),
    (MaterialType::RedGarnet, 2.7),
    (MaterialType::RedJade, 2.0),
    (MaterialType::RoseQuartz, 2.1),
    (MaterialType::Ruby, 5.0),
    (MaterialType::Sapphire, 5.5),
    (MaterialType::SmokeyQuartz, 1.7),
    (MaterialType::Sunstone, 3.3),
    (MaterialType::TigerEye, 1.3),
    (MaterialType::Tourmaline, 3.7),
    (MaterialType::Turquoise, 1.7),
    (MaterialType::WhiteJade, 1.7),
    (MaterialType::WhiteQuartz, 1.6),
    (MaterialType::WhiteSapphire, 4.3),
    (MaterialType::YellowGarnet, 2.8),
    (MaterialType::YellowTopaz, 3.0),
    (MaterialType::Zircon, 3.0),
    (MaterialType::Ivory, 2.2),
    (MaterialType::Leather, 0.2),
    (MaterialType::ArmoredilloHide, 2.0),
    (MaterialType::GromnieHide, 1.3),
    (MaterialType::ReedSharkHide, 2.2),
    (MaterialType::Brass, 0.5),
    (MaterialType::Bronze, 0.0),
    (MaterialType::Copper, 1.0),
    (MaterialType::Gold, 3.0),
    (MaterialType::Iron, 0.0),
    (MaterialType::Pyreal, 5.0),
    (MaterialType::Silver, 2.0),
    (MaterialType::Steel, 1.0),
    (MaterialType::Alabaster, 1.5),
    (MaterialType::Granite, 0.0),
    (MaterialType::Marble, 1.8),
    (MaterialType::Obsidian, 1.2),
    (MaterialType::Sandstone, 0.0),
    (MaterialType::Serpentine, 2.0),
    (MaterialType::Ebony, 2.0),
    (MaterialType::Mahogany, 1.5),
    (MaterialType::Oak, 0.5),
    (MaterialType::Pine, 0.0),
    (MaterialType::Teak, 1.5),
];
