// Ported from ACE (ACEmulator), AGPL-3.0: Source/ACE.Entity/Enum/PlayScript.cs
// @generated from ACE's `Source/ACE.Entity/Enum/PlayScript.cs`; do not edit by hand

/// ACE enum `PlayScript`, underlying `uint`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Default)]
#[repr(transparent)]
pub struct PlayScript(pub u32);

#[allow(non_upper_case_globals)]
impl PlayScript {
    pub const Invalid: Self = Self(0);
    pub const Test1: Self = Self(1);
    pub const Test2: Self = Self(2);
    pub const Test3: Self = Self(3);
    pub const Launch: Self = Self(4);
    pub const Explode: Self = Self(5);
    pub const AttribUpRed: Self = Self(6);
    pub const AttribDownRed: Self = Self(7);
    pub const AttribUpOrange: Self = Self(8);
    pub const AttribDownOrange: Self = Self(9);
    pub const AttribUpYellow: Self = Self(10);
    pub const AttribDownYellow: Self = Self(11);
    pub const AttribUpGreen: Self = Self(12);
    pub const AttribDownGreen: Self = Self(13);
    pub const AttribUpBlue: Self = Self(14);
    pub const AttribDownBlue: Self = Self(15);
    pub const AttribUpPurple: Self = Self(16);
    pub const AttribDownPurple: Self = Self(17);
    pub const SkillUpRed: Self = Self(18);
    pub const SkillDownRed: Self = Self(19);
    pub const SkillUpOrange: Self = Self(20);
    pub const SkillDownOrange: Self = Self(21);
    pub const SkillUpYellow: Self = Self(22);
    pub const SkillDownYellow: Self = Self(23);
    pub const SkillUpGreen: Self = Self(24);
    pub const SkillDownGreen: Self = Self(25);
    pub const SkillUpBlue: Self = Self(26);
    pub const SkillDownBlue: Self = Self(27);
    pub const SkillUpPurple: Self = Self(28);
    pub const SkillDownPurple: Self = Self(29);
    pub const SkillDownBlack: Self = Self(30);
    pub const HealthUpRed: Self = Self(31);
    pub const HealthDownRed: Self = Self(32);
    pub const HealthUpBlue: Self = Self(33);
    pub const HealthDownBlue: Self = Self(34);
    pub const HealthUpYellow: Self = Self(35);
    pub const HealthDownYellow: Self = Self(36);
    pub const RegenUpRed: Self = Self(37);
    pub const RegenDownREd: Self = Self(38);
    pub const RegenUpBlue: Self = Self(39);
    pub const RegenDownBlue: Self = Self(40);
    pub const RegenUpYellow: Self = Self(41);
    pub const RegenDownYellow: Self = Self(42);
    pub const ShieldUpRed: Self = Self(43);
    pub const ShieldDownRed: Self = Self(44);
    pub const ShieldUpOrange: Self = Self(45);
    pub const ShieldDownOrange: Self = Self(46);
    pub const ShieldUpYellow: Self = Self(47);
    pub const ShieldDownYellow: Self = Self(48);
    pub const ShieldUpGreen: Self = Self(49);
    pub const ShieldDownGreen: Self = Self(50);
    pub const ShieldUpBlue: Self = Self(51);
    pub const ShieldDownBlue: Self = Self(52);
    pub const ShieldUpPurple: Self = Self(53);
    pub const ShieldDownPurple: Self = Self(54);
    pub const ShieldUpGrey: Self = Self(55);
    pub const ShieldDownGrey: Self = Self(56);
    pub const EnchantUpRed: Self = Self(57);
    pub const EnchantDownRed: Self = Self(58);
    pub const EnchantUpOrange: Self = Self(59);
    pub const EnchantDownOrange: Self = Self(60);
    pub const EnchantUpYellow: Self = Self(61);
    pub const EnchantDownYellow: Self = Self(62);
    pub const EnchantUpGreen: Self = Self(63);
    pub const EnchantDownGreen: Self = Self(64);
    pub const EnchantUpBlue: Self = Self(65);
    pub const EnchantDownBlue: Self = Self(66);
    pub const EnchantUpPurple: Self = Self(67);
    pub const EnchantDownPurple: Self = Self(68);
    pub const VitaeUpWhite: Self = Self(69);
    pub const VitaeDownBlack: Self = Self(70);
    pub const VisionUpWhite: Self = Self(71);
    pub const VisionDownBlack: Self = Self(72);
    pub const SwapHealth_Red_To_Yellow: Self = Self(73);
    pub const SwapHealth_Red_To_Blue: Self = Self(74);
    pub const SwapHealth_Yellow_To_Red: Self = Self(75);
    pub const SwapHealth_Yellow_To_Blue: Self = Self(76);
    pub const SwapHealth_Blue_To_Red: Self = Self(77);
    pub const SwapHealth_Blue_To_Yellow: Self = Self(78);
    pub const TransUpWhite: Self = Self(79);
    pub const TransDownBlack: Self = Self(80);
    pub const Fizzle: Self = Self(81);
    pub const PortalEntry: Self = Self(82);
    pub const PortalExit: Self = Self(83);
    pub const BreatheFlame: Self = Self(84);
    pub const BreatheFrost: Self = Self(85);
    pub const BreatheAcid: Self = Self(86);
    pub const BreatheLightning: Self = Self(87);
    pub const Create: Self = Self(88);
    pub const Destroy: Self = Self(89);
    pub const ProjectileCollision: Self = Self(90);
    pub const SplatterLowLeftBack: Self = Self(91);
    pub const SplatterLowLeftFront: Self = Self(92);
    pub const SplatterLowRightBack: Self = Self(93);
    pub const SplatterLowRightFront: Self = Self(94);
    pub const SplatterMidLeftBack: Self = Self(95);
    pub const SplatterMidLeftFront: Self = Self(96);
    pub const SplatterMidRightBack: Self = Self(97);
    pub const SplatterMidRightFront: Self = Self(98);
    pub const SplatterUpLeftBack: Self = Self(99);
    pub const SplatterUpLeftFront: Self = Self(100);
    pub const SplatterUpRightBack: Self = Self(101);
    pub const SplatterUpRightFront: Self = Self(102);
    pub const SparkLowLeftBack: Self = Self(103);
    pub const SparkLowLeftFront: Self = Self(104);
    pub const SparkLowRightBack: Self = Self(105);
    pub const SparkLowRightFront: Self = Self(106);
    pub const SparkMidLeftBack: Self = Self(107);
    pub const SparkMidLeftFront: Self = Self(108);
    pub const SparkMidRightBack: Self = Self(109);
    pub const SparkMidRightFront: Self = Self(110);
    pub const SparkUpLeftBack: Self = Self(111);
    pub const SparkUpLeftFront: Self = Self(112);
    pub const SparkUpRightBack: Self = Self(113);
    pub const SparkUpRightFront: Self = Self(114);
    pub const PortalStorm: Self = Self(115);
    pub const Hide: Self = Self(116);
    pub const UnHide: Self = Self(117);
    pub const Hidden: Self = Self(118);
    pub const DisappearDestroy: Self = Self(119);
    pub const SpecialState1: Self = Self(120);
    pub const SpecialState2: Self = Self(121);
    pub const SpecialState3: Self = Self(122);
    pub const SpecialState4: Self = Self(123);
    pub const SpecialState5: Self = Self(124);
    pub const SpecialState6: Self = Self(125);
    pub const SpecialState7: Self = Self(126);
    pub const SpecialState8: Self = Self(127);
    pub const SpecialState9: Self = Self(128);
    pub const SpecialState0: Self = Self(129);
    pub const SpecialStateRed: Self = Self(130);
    pub const SpecialStateOrange: Self = Self(131);
    pub const SpecialStateYellow: Self = Self(132);
    pub const SpecialStateGreen: Self = Self(133);
    pub const SpecialStateBlue: Self = Self(134);
    pub const SpecialStatePurple: Self = Self(135);
    pub const SpecialStateWhite: Self = Self(136);
    pub const SpecialStateBlack: Self = Self(137);
    pub const LevelUp: Self = Self(138);
    pub const EnchantUpGrey: Self = Self(139);
    pub const EnchantDownGrey: Self = Self(140);
    pub const WeddingBliss: Self = Self(141);
    pub const EnchantUpWhite: Self = Self(142);
    pub const EnchantDownWhite: Self = Self(143);
    pub const CampingMastery: Self = Self(144);
    pub const CampingIneptitude: Self = Self(145);
    pub const DispelLife: Self = Self(146);
    pub const DispelCreature: Self = Self(147);
    pub const DispelAll: Self = Self(148);
    pub const BunnySmite: Self = Self(149);
    pub const BaelZharonSmite: Self = Self(150);
    pub const WeddingSteele: Self = Self(151);
    pub const RestrictionEffectBlue: Self = Self(152);
    pub const RestrictionEffectGreen: Self = Self(153);
    pub const RestrictionEffectGold: Self = Self(154);
    pub const LayingofHands: Self = Self(155);
    pub const AugmentationUseAttribute: Self = Self(156);
    pub const AugmentationUseSkill: Self = Self(157);
    pub const AugmentationUseResistances: Self = Self(158);
    pub const AugmentationUseOther: Self = Self(159);
    pub const BlackMadness: Self = Self(160);
    pub const AetheriaLevelUp: Self = Self(161);
    pub const AetheriaSurgeDestruction: Self = Self(162);
    pub const AetheriaSurgeProtection: Self = Self(163);
    pub const AetheriaSurgeRegeneration: Self = Self(164);
    pub const AetheriaSurgeAffliction: Self = Self(165);
    pub const AetheriaSurgeFestering: Self = Self(166);
    pub const HealthDownVoid: Self = Self(167);
    pub const RegenDownVoid: Self = Self(168);
    pub const SkillDownVoid: Self = Self(169);
    pub const DirtyFightingHealDebuff: Self = Self(170);
    pub const DirtyFightingAttackDebuff: Self = Self(171);
    pub const DirtyFightingDefenseDebuff: Self = Self(172);
    pub const DirtyFightingDamageOverTime: Self = Self(173);
}

impl PlayScript {
    /// Every declared member, aliases included, in .NET `Enum.GetValues` order.
    pub const ALL: &'static [Self] = &[Self::Invalid, Self::Test1, Self::Test2, Self::Test3, Self::Launch, Self::Explode, Self::AttribUpRed, Self::AttribDownRed, Self::AttribUpOrange, Self::AttribDownOrange, Self::AttribUpYellow, Self::AttribDownYellow, Self::AttribUpGreen, Self::AttribDownGreen, Self::AttribUpBlue, Self::AttribDownBlue, Self::AttribUpPurple, Self::AttribDownPurple, Self::SkillUpRed, Self::SkillDownRed, Self::SkillUpOrange, Self::SkillDownOrange, Self::SkillUpYellow, Self::SkillDownYellow, Self::SkillUpGreen, Self::SkillDownGreen, Self::SkillUpBlue, Self::SkillDownBlue, Self::SkillUpPurple, Self::SkillDownPurple, Self::SkillDownBlack, Self::HealthUpRed, Self::HealthDownRed, Self::HealthUpBlue, Self::HealthDownBlue, Self::HealthUpYellow, Self::HealthDownYellow, Self::RegenUpRed, Self::RegenDownREd, Self::RegenUpBlue, Self::RegenDownBlue, Self::RegenUpYellow, Self::RegenDownYellow, Self::ShieldUpRed, Self::ShieldDownRed, Self::ShieldUpOrange, Self::ShieldDownOrange, Self::ShieldUpYellow, Self::ShieldDownYellow, Self::ShieldUpGreen, Self::ShieldDownGreen, Self::ShieldUpBlue, Self::ShieldDownBlue, Self::ShieldUpPurple, Self::ShieldDownPurple, Self::ShieldUpGrey, Self::ShieldDownGrey, Self::EnchantUpRed, Self::EnchantDownRed, Self::EnchantUpOrange, Self::EnchantDownOrange, Self::EnchantUpYellow, Self::EnchantDownYellow, Self::EnchantUpGreen, Self::EnchantDownGreen, Self::EnchantUpBlue, Self::EnchantDownBlue, Self::EnchantUpPurple, Self::EnchantDownPurple, Self::VitaeUpWhite, Self::VitaeDownBlack, Self::VisionUpWhite, Self::VisionDownBlack, Self::SwapHealth_Red_To_Yellow, Self::SwapHealth_Red_To_Blue, Self::SwapHealth_Yellow_To_Red, Self::SwapHealth_Yellow_To_Blue, Self::SwapHealth_Blue_To_Red, Self::SwapHealth_Blue_To_Yellow, Self::TransUpWhite, Self::TransDownBlack, Self::Fizzle, Self::PortalEntry, Self::PortalExit, Self::BreatheFlame, Self::BreatheFrost, Self::BreatheAcid, Self::BreatheLightning, Self::Create, Self::Destroy, Self::ProjectileCollision, Self::SplatterLowLeftBack, Self::SplatterLowLeftFront, Self::SplatterLowRightBack, Self::SplatterLowRightFront, Self::SplatterMidLeftBack, Self::SplatterMidLeftFront, Self::SplatterMidRightBack, Self::SplatterMidRightFront, Self::SplatterUpLeftBack, Self::SplatterUpLeftFront, Self::SplatterUpRightBack, Self::SplatterUpRightFront, Self::SparkLowLeftBack, Self::SparkLowLeftFront, Self::SparkLowRightBack, Self::SparkLowRightFront, Self::SparkMidLeftBack, Self::SparkMidLeftFront, Self::SparkMidRightBack, Self::SparkMidRightFront, Self::SparkUpLeftBack, Self::SparkUpLeftFront, Self::SparkUpRightBack, Self::SparkUpRightFront, Self::PortalStorm, Self::Hide, Self::UnHide, Self::Hidden, Self::DisappearDestroy, Self::SpecialState1, Self::SpecialState2, Self::SpecialState3, Self::SpecialState4, Self::SpecialState5, Self::SpecialState6, Self::SpecialState7, Self::SpecialState8, Self::SpecialState9, Self::SpecialState0, Self::SpecialStateRed, Self::SpecialStateOrange, Self::SpecialStateYellow, Self::SpecialStateGreen, Self::SpecialStateBlue, Self::SpecialStatePurple, Self::SpecialStateWhite, Self::SpecialStateBlack, Self::LevelUp, Self::EnchantUpGrey, Self::EnchantDownGrey, Self::WeddingBliss, Self::EnchantUpWhite, Self::EnchantDownWhite, Self::CampingMastery, Self::CampingIneptitude, Self::DispelLife, Self::DispelCreature, Self::DispelAll, Self::BunnySmite, Self::BaelZharonSmite, Self::WeddingSteele, Self::RestrictionEffectBlue, Self::RestrictionEffectGreen, Self::RestrictionEffectGold, Self::LayingofHands, Self::AugmentationUseAttribute, Self::AugmentationUseSkill, Self::AugmentationUseResistances, Self::AugmentationUseOther, Self::BlackMadness, Self::AetheriaLevelUp, Self::AetheriaSurgeDestruction, Self::AetheriaSurgeProtection, Self::AetheriaSurgeRegeneration, Self::AetheriaSurgeAffliction, Self::AetheriaSurgeFestering, Self::HealthDownVoid, Self::RegenDownVoid, Self::SkillDownVoid, Self::DirtyFightingHealDebuff, Self::DirtyFightingAttackDebuff, Self::DirtyFightingDefenseDebuff, Self::DirtyFightingDamageOverTime];
    /// The name of each entry of [`Self::ALL`], in the same order.
    pub const NAMES: &'static [&'static str] = &["Invalid", "Test1", "Test2", "Test3", "Launch", "Explode", "AttribUpRed", "AttribDownRed", "AttribUpOrange", "AttribDownOrange", "AttribUpYellow", "AttribDownYellow", "AttribUpGreen", "AttribDownGreen", "AttribUpBlue", "AttribDownBlue", "AttribUpPurple", "AttribDownPurple", "SkillUpRed", "SkillDownRed", "SkillUpOrange", "SkillDownOrange", "SkillUpYellow", "SkillDownYellow", "SkillUpGreen", "SkillDownGreen", "SkillUpBlue", "SkillDownBlue", "SkillUpPurple", "SkillDownPurple", "SkillDownBlack", "HealthUpRed", "HealthDownRed", "HealthUpBlue", "HealthDownBlue", "HealthUpYellow", "HealthDownYellow", "RegenUpRed", "RegenDownREd", "RegenUpBlue", "RegenDownBlue", "RegenUpYellow", "RegenDownYellow", "ShieldUpRed", "ShieldDownRed", "ShieldUpOrange", "ShieldDownOrange", "ShieldUpYellow", "ShieldDownYellow", "ShieldUpGreen", "ShieldDownGreen", "ShieldUpBlue", "ShieldDownBlue", "ShieldUpPurple", "ShieldDownPurple", "ShieldUpGrey", "ShieldDownGrey", "EnchantUpRed", "EnchantDownRed", "EnchantUpOrange", "EnchantDownOrange", "EnchantUpYellow", "EnchantDownYellow", "EnchantUpGreen", "EnchantDownGreen", "EnchantUpBlue", "EnchantDownBlue", "EnchantUpPurple", "EnchantDownPurple", "VitaeUpWhite", "VitaeDownBlack", "VisionUpWhite", "VisionDownBlack", "SwapHealth_Red_To_Yellow", "SwapHealth_Red_To_Blue", "SwapHealth_Yellow_To_Red", "SwapHealth_Yellow_To_Blue", "SwapHealth_Blue_To_Red", "SwapHealth_Blue_To_Yellow", "TransUpWhite", "TransDownBlack", "Fizzle", "PortalEntry", "PortalExit", "BreatheFlame", "BreatheFrost", "BreatheAcid", "BreatheLightning", "Create", "Destroy", "ProjectileCollision", "SplatterLowLeftBack", "SplatterLowLeftFront", "SplatterLowRightBack", "SplatterLowRightFront", "SplatterMidLeftBack", "SplatterMidLeftFront", "SplatterMidRightBack", "SplatterMidRightFront", "SplatterUpLeftBack", "SplatterUpLeftFront", "SplatterUpRightBack", "SplatterUpRightFront", "SparkLowLeftBack", "SparkLowLeftFront", "SparkLowRightBack", "SparkLowRightFront", "SparkMidLeftBack", "SparkMidLeftFront", "SparkMidRightBack", "SparkMidRightFront", "SparkUpLeftBack", "SparkUpLeftFront", "SparkUpRightBack", "SparkUpRightFront", "PortalStorm", "Hide", "UnHide", "Hidden", "DisappearDestroy", "SpecialState1", "SpecialState2", "SpecialState3", "SpecialState4", "SpecialState5", "SpecialState6", "SpecialState7", "SpecialState8", "SpecialState9", "SpecialState0", "SpecialStateRed", "SpecialStateOrange", "SpecialStateYellow", "SpecialStateGreen", "SpecialStateBlue", "SpecialStatePurple", "SpecialStateWhite", "SpecialStateBlack", "LevelUp", "EnchantUpGrey", "EnchantDownGrey", "WeddingBliss", "EnchantUpWhite", "EnchantDownWhite", "CampingMastery", "CampingIneptitude", "DispelLife", "DispelCreature", "DispelAll", "BunnySmite", "BaelZharonSmite", "WeddingSteele", "RestrictionEffectBlue", "RestrictionEffectGreen", "RestrictionEffectGold", "LayingofHands", "AugmentationUseAttribute", "AugmentationUseSkill", "AugmentationUseResistances", "AugmentationUseOther", "BlackMadness", "AetheriaLevelUp", "AetheriaSurgeDestruction", "AetheriaSurgeProtection", "AetheriaSurgeRegeneration", "AetheriaSurgeAffliction", "AetheriaSurgeFestering", "HealthDownVoid", "RegenDownVoid", "SkillDownVoid", "DirtyFightingHealDebuff", "DirtyFightingAttackDebuff", "DirtyFightingDefenseDebuff", "DirtyFightingDamageOverTime"];
    /// Indices into [`Self::NAMES`], sorted by ordinal name.
    const NAME_ORDER: &'static [u16] = &[161, 165, 162, 166, 163, 164, 15, 13, 9, 17, 7, 11, 14, 12, 8, 16, 6, 10, 156, 159, 158, 157, 150, 160, 86, 84, 85, 87, 149, 145, 144, 88, 89, 171, 173, 172, 170, 119, 148, 147, 146, 66, 64, 140, 60, 68, 58, 143, 62, 65, 63, 139, 59, 67, 57, 142, 61, 5, 81, 34, 32, 167, 36, 33, 31, 35, 118, 116, 0, 4, 155, 138, 82, 83, 115, 90, 40, 38, 168, 42, 39, 37, 41, 152, 154, 153, 52, 50, 56, 46, 54, 44, 48, 51, 49, 55, 45, 53, 43, 47, 30, 27, 25, 21, 29, 19, 169, 23, 26, 24, 20, 28, 18, 22, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 129, 120, 121, 122, 123, 124, 125, 126, 127, 128, 137, 134, 133, 131, 135, 130, 136, 132, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 77, 78, 74, 73, 76, 75, 1, 2, 3, 80, 79, 117, 72, 71, 70, 69, 141, 151];
}

super::support::ace_enum!(PlayScript, u32, plain);
super::support::ace_enum_from!(PlayScript, u32 => u64, i64);
