// Ported from ACE (ACEmulator), AGPL-3.0: Source/ACE.Entity/Enum/SpellId.cs

/// ACE's `SpellExtensions` static sets. ACE keeps them in `HashSet<SpellId>`, which (with no
/// removals) enumerates in insertion order; the slices keep that order.
pub mod spell_extensions {
    use crate::enums::SpellId;

    /// The spells used by the Dirty Fighting skill.
    // ACE: SpellExtensions.DirtyFightingSpells
    pub const DIRTY_FIGHTING_SPELLS: &[SpellId] = &[
        SpellId::DF_Specialized_AttackDebuff,
        SpellId::DF_Specialized_Bleed,
        SpellId::DF_Specialized_DefenseDebuff,
        SpellId::DF_Specialized_HealingDebuff,
        SpellId::DF_Trained_AttackDebuff,
        SpellId::DF_Trained_Bleed,
        SpellId::DF_Trained_DefenseDebuff,
        SpellId::DF_Trained_HealingDebuff,
    ];

    /// The spells used by the Void Magic skill.
    // ACE: SpellExtensions.VoidMagicSpells
    pub const VOID_MAGIC_SPELLS: &[SpellId] = &[
        SpellId::Corrosion1,
        SpellId::Corrosion2,
        SpellId::Corrosion3,
        SpellId::Corrosion4,
        SpellId::Corrosion5,
        SpellId::Corrosion6,
        SpellId::Corrosion7,
        SpellId::Corrosion8,
        SpellId::Corruption1,
        SpellId::Corruption2,
        SpellId::Corruption3,
        SpellId::Corruption4,
        SpellId::Corruption5,
        SpellId::Corruption6,
        SpellId::Corruption7,
        SpellId::Corruption8,
        SpellId::CurseDestructionOther1,
        SpellId::CurseDestructionOther2,
        SpellId::CurseDestructionOther3,
        SpellId::CurseDestructionOther4,
        SpellId::CurseDestructionOther5,
        SpellId::CurseDestructionOther6,
        SpellId::CurseDestructionOther7,
        SpellId::CurseDestructionOther8,
        SpellId::CurseFestering1,
        SpellId::CurseFestering2,
        SpellId::CurseFestering3,
        SpellId::CurseFestering4,
        SpellId::CurseFestering5,
        SpellId::CurseFestering6,
        SpellId::CurseFestering7,
        SpellId::CurseFestering8,
        SpellId::NetherArc1,
        SpellId::NetherArc2,
        SpellId::NetherArc3,
        SpellId::NetherArc4,
        SpellId::NetherArc5,
        SpellId::NetherArc6,
        SpellId::NetherArc7,
        SpellId::NetherArc8,
        SpellId::NetherBlast1,
        SpellId::NetherBlast2,
        SpellId::NetherBlast3,
        SpellId::NetherBlast4,
        SpellId::NetherBlast5,
        SpellId::NetherBlast6,
        SpellId::NetherBlast7,
        SpellId::NetherBlast8,
        SpellId::NetherBolt1,
        SpellId::NetherBolt2,
        SpellId::NetherBolt3,
        SpellId::NetherBolt4,
        SpellId::NetherBolt5,
        SpellId::NetherBolt6,
        SpellId::NetherBolt7,
        SpellId::NetherBolt8,
        SpellId::NetherRing,
        SpellId::CloudedSoulII,
        SpellId::RingOfSkullsII,
        SpellId::NetherStreak1,
        SpellId::NetherStreak2,
        SpellId::NetherStreak3,
        SpellId::NetherStreak4,
        SpellId::NetherStreak5,
        SpellId::NetherStreak6,
        SpellId::NetherStreak7,
        SpellId::NetherStreak8,
        SpellId::CurseWeakness1,
        SpellId::CurseWeakness2,
        SpellId::CurseWeakness3,
        SpellId::CurseWeakness4,
        SpellId::CurseWeakness5,
        SpellId::CurseWeakness6,
        SpellId::CurseWeakness7,
        SpellId::CurseWeakness8,
    ];
}
