//! The page's `KeyboardEvent.code` strings as the shared key codes. The two name the same
//! physical keys with the same words, so this is a name lookup over the keys the shared key tables
//! know; a key they do not know has no code here either.

use dereth_input::keys::KeyCode as K;

/// The key code `code` names, or `None` for a key the client's tables do not map.
#[must_use]
pub fn from_dom(code: &str) -> Option<K> {
    Some(match code {
        "AltLeft" => K::AltLeft,
        "AltRight" => K::AltRight,
        "ArrowDown" => K::ArrowDown,
        "ArrowLeft" => K::ArrowLeft,
        "ArrowRight" => K::ArrowRight,
        "ArrowUp" => K::ArrowUp,
        "AudioVolumeDown" => K::AudioVolumeDown,
        "AudioVolumeMute" => K::AudioVolumeMute,
        "AudioVolumeUp" => K::AudioVolumeUp,
        "Backquote" => K::Backquote,
        "Backslash" => K::Backslash,
        "Backspace" => K::Backspace,
        "BracketLeft" => K::BracketLeft,
        "BracketRight" => K::BracketRight,
        "BrowserBack" => K::BrowserBack,
        "BrowserFavorites" => K::BrowserFavorites,
        "BrowserForward" => K::BrowserForward,
        "BrowserHome" => K::BrowserHome,
        "BrowserRefresh" => K::BrowserRefresh,
        "BrowserSearch" => K::BrowserSearch,
        "BrowserStop" => K::BrowserStop,
        "CapsLock" => K::CapsLock,
        "Comma" => K::Comma,
        "ContextMenu" => K::ContextMenu,
        "ControlLeft" => K::ControlLeft,
        "ControlRight" => K::ControlRight,
        "Convert" => K::Convert,
        "Delete" => K::Delete,
        "Digit0" => K::Digit0,
        "Digit1" => K::Digit1,
        "Digit2" => K::Digit2,
        "Digit3" => K::Digit3,
        "Digit4" => K::Digit4,
        "Digit5" => K::Digit5,
        "Digit6" => K::Digit6,
        "Digit7" => K::Digit7,
        "Digit8" => K::Digit8,
        "Digit9" => K::Digit9,
        "End" => K::End,
        "Enter" => K::Enter,
        "Equal" => K::Equal,
        "Escape" => K::Escape,
        "F1" => K::F1,
        "F10" => K::F10,
        "F11" => K::F11,
        "F12" => K::F12,
        "F13" => K::F13,
        "F14" => K::F14,
        "F15" => K::F15,
        "F16" => K::F16,
        "F17" => K::F17,
        "F18" => K::F18,
        "F19" => K::F19,
        "F2" => K::F2,
        "F20" => K::F20,
        "F21" => K::F21,
        "F22" => K::F22,
        "F23" => K::F23,
        "F24" => K::F24,
        "F3" => K::F3,
        "F4" => K::F4,
        "F5" => K::F5,
        "F6" => K::F6,
        "F7" => K::F7,
        "F8" => K::F8,
        "F9" => K::F9,
        "Home" => K::Home,
        "Insert" => K::Insert,
        "IntlBackslash" => K::IntlBackslash,
        "IntlRo" => K::IntlRo,
        "IntlYen" => K::IntlYen,
        "KanaMode" => K::KanaMode,
        "KeyA" => K::KeyA,
        "KeyB" => K::KeyB,
        "KeyC" => K::KeyC,
        "KeyD" => K::KeyD,
        "KeyE" => K::KeyE,
        "KeyF" => K::KeyF,
        "KeyG" => K::KeyG,
        "KeyH" => K::KeyH,
        "KeyI" => K::KeyI,
        "KeyJ" => K::KeyJ,
        "KeyK" => K::KeyK,
        "KeyL" => K::KeyL,
        "KeyM" => K::KeyM,
        "KeyN" => K::KeyN,
        "KeyO" => K::KeyO,
        "KeyP" => K::KeyP,
        "KeyQ" => K::KeyQ,
        "KeyR" => K::KeyR,
        "KeyS" => K::KeyS,
        "KeyT" => K::KeyT,
        "KeyU" => K::KeyU,
        "KeyV" => K::KeyV,
        "KeyW" => K::KeyW,
        "KeyX" => K::KeyX,
        "KeyY" => K::KeyY,
        "KeyZ" => K::KeyZ,
        "Lang1" => K::Lang1,
        "Lang2" => K::Lang2,
        "LaunchApp1" => K::LaunchApp1,
        "LaunchApp2" => K::LaunchApp2,
        "LaunchMail" => K::LaunchMail,
        "MediaPlayPause" => K::MediaPlayPause,
        "MediaSelect" => K::MediaSelect,
        "MediaStop" => K::MediaStop,
        "MediaTrackNext" => K::MediaTrackNext,
        "MediaTrackPrevious" => K::MediaTrackPrevious,
        "Minus" => K::Minus,
        "NonConvert" => K::NonConvert,
        "NumLock" => K::NumLock,
        "Numpad0" => K::Numpad0,
        "Numpad1" => K::Numpad1,
        "Numpad2" => K::Numpad2,
        "Numpad3" => K::Numpad3,
        "Numpad4" => K::Numpad4,
        "Numpad5" => K::Numpad5,
        "Numpad6" => K::Numpad6,
        "Numpad7" => K::Numpad7,
        "Numpad8" => K::Numpad8,
        "Numpad9" => K::Numpad9,
        "NumpadAdd" => K::NumpadAdd,
        "NumpadComma" => K::NumpadComma,
        "NumpadDecimal" => K::NumpadDecimal,
        "NumpadDivide" => K::NumpadDivide,
        "NumpadEnter" => K::NumpadEnter,
        "NumpadEqual" => K::NumpadEqual,
        "NumpadMultiply" => K::NumpadMultiply,
        "NumpadSubtract" => K::NumpadSubtract,
        "PageDown" => K::PageDown,
        "PageUp" => K::PageUp,
        "Pause" => K::Pause,
        "Period" => K::Period,
        "Power" => K::Power,
        "PrintScreen" => K::PrintScreen,
        "Quote" => K::Quote,
        "ScrollLock" => K::ScrollLock,
        "Semicolon" => K::Semicolon,
        "ShiftLeft" => K::ShiftLeft,
        "ShiftRight" => K::ShiftRight,
        "Slash" => K::Slash,
        "Space" => K::Space,
        "SuperLeft" => K::SuperLeft,
        "SuperRight" => K::SuperRight,
        "Tab" => K::Tab,
        "Unidentified" => K::Unidentified,
        _ => return None,
    })
}
#[cfg(test)]
mod tests {
    use super::*;

    /// A letter, a digit, a function key and the extended block's arrows are found by the name
    /// the page gives them, and an unknown name is not.
    #[test]
    fn the_page_s_key_names_are_the_shared_key_codes() {
        assert_eq!(from_dom("KeyW"), Some(K::KeyW));
        assert_eq!(from_dom("Digit1"), Some(K::Digit1));
        assert_eq!(from_dom("F4"), Some(K::F4));
        assert_eq!(from_dom("ArrowUp"), Some(K::ArrowUp));
        assert_eq!(from_dom("NoSuchKey"), None);
    }
}
